import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.min.css";
import "@/styles/global.scss";
import Providers from "@/components/Providers/Providers";

export const metadata: Metadata = {
  title: "Pet shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body suppressHydrationWarning={true}>{children}</body>
      </Providers>
    </html>
  );
}
